version: '3'
services:
  ldap:
    build: .
    image: mitel-ldap-proxy
    ports:
      - "10389:10389"
    environment:
      - BIND_PASSWORD=supersecret
      - BASE_DN=dc=baraddur, dc=mordor
      - BIND_THINGY=cn=sauron
      - PHONEBOOK_THINGY=ou=Phonebook, dc=baraddur, dc=mordor
      #- DEV=true
      - DEV=false
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password

  # Database and admin tools
  db:
    image: mariadb:10.8.3-jammy
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      # would not create a database if MYSQL_DATABASE is not set
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mariadb-data:/var/lib/mysql
  #  postgres:
  #    image: postgres:13.2-alpine
  #    ports:
  #      - 5432:5432
  #    environment:
  #      # does not seem to work
  #      - POSTGRES_DATABASE=db
  #      # is (in contrast to mariadb) the superuser
  #      - POSTGRES_USER=user
  #      - POSTGRES_PASSWORD=password
  phpmyadmin:
    image: phpmyadmin:5.2.0
    ports:
      - 8090:80
    environment:
      - PMA_HOST=db
      - UPLOAD_LIMIT=1024000
#  adminer:
#    image: adminer:4.7.8-standalone
#    ports:
#      - 8091:8080
#    environment:
#      - ADMINER_DEFAULT_SERVER=db

volumes:
  #  greeting-data:
  mariadb-data: